import DashboardWrapper from '@/components/wrapper/DashboardWrapper'
import { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Admin ",
    description: "Generated by create next app",
};


const AdminLayout = ({ children }: { children: React.ReactNode }) => {



    return (

        <div className='h-screen '>

            <DashboardWrapper  >
                {
                    children
                }
            </DashboardWrapper>
        </div>

    )
}


export default AdminLayout;